apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DB_PASSWORD: {{ .Values.app.env.DB_PASSWORD | quote | b64enc }}
  EMAIL_PASSWORD: {{ .Values.app.env.EMAIL_PASSWORD | quote | b64enc }}
