apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
  selector:
    app: {{ .Release.Name }}-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  selector:
    app: {{ .Release.Name }}-mysql
